name: smile_hair_clinic
description: A Flutter app for guided hair clinic photo capture
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # Firebase packages
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

  # Camera & sensors
  camera: ^0.11.3



  sensors_plus: ^7.0.0




  # ML Kit face detection
  google_mlkit_face_detection: ^0.13.1



  # Audio
  audioplayers: ^6.5.1

  # File paths
  path_provider: ^2.0.16

  # Others
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
